In [1]:
import pandas as pd
import os
path = r'D:\Projects\Software_Engineering\Artificial_Intelligence\Huawei_Internship_16_Sep/Datasets'

df = pd.read_csv(os.path.join(path, 'Data.csv'))
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany   NaN     10.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  50.0      NaN        No
7   France  48.0      NaN       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

* labelencoder: used with 1D array only, it's used to convert categorical labels (strings or other non-numeric data) into numerical form.

* OrdinalEncoder: Encodes categorical variables as integers (similar to LabelEncoder, but for multiple columns).

* OneHotEncoder:

Input:
- [['cat'], ['dog'], ['fish'], ['dog'], ['cat']]

Output:
- 'cat' → [1, 0, 0]
- 'dog' → [0, 1, 0]
- 'fish' → [0, 0, 1]


ColumnTransformer: This allows you to apply different transformations to specific columns

Every Encoder have the following Components:
- fit(): This method learns the unique classes (labels) in the data.
- transform(): This method converts the labels into numeric values after learning their mapping.
- fit_transform(): This is a combination of the above two steps. It first learns the classes with fit(), then immediately transforms them into numerical values with transform() in a single step.

In [2]:
from sklearn.preprocessing import LabelEncoder

print(df['Purchased'])
df['Purchased'] = LabelEncoder().fit_transform(df['Purchased'])
print(df['Purchased'])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, MinMaxScaler

# tf = ColumnTransformer(transformers=[name of Transformer, type of Transformer, cols in dataset to apply])
tf = ColumnTransformer(
    transformers=[
        ('Country_encoder', OneHotEncoder(), ['Country']),
        ('age_encoder', OrdinalEncoder(), ['Age']),
        ('Salary_encoder', MinMaxScaler(), ['Salary'])
        ],
        remainder='passthrough' # Keep other columns as-is
    )

result = tf.fit_transform(df)
result = pd.DataFrame(result, columns=['France', 'Germany', 'Spain', 'Age', 'Salary', 'Purchased'])


print(result)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object
0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purchased, dtype: int32
   France  Germany  Spain  Age    Salary  Purchased
0     1.0      0.0    0.0  5.0  0.867454        0.0
1     0.0      0.0    1.0  0.0  0.578262        1.0
2     0.0      1.0    0.0  1.0  0.650560        0.0
3     0.0      0.0    1.0  4.0  0.734908        0.0
4     0.0      1.0    0.0  NaN  0.000000        1.0
5     1.0      0.0    0.0  2.0  0.698759        1.0
6     0.0      0.0    1.0  7.0       NaN        0.0
7     1.0      0.0    0.0  6.0       NaN        1.0
8     0.0      1.0    0.0  7.0  1.000000        0.0
9     1.0      0.0    0.0  3.0  0.807206        1.0


In [3]:
import pandas as pd

data = pd.read_csv(os.path.join(path, 'Data.csv'))
X = data.iloc[ : , 0:-1].values
y = data.iloc[ : , -1].values
print(f'X: {X}')
print(f'y: {y}')
print('\n\n')


from sklearn.preprocessing import LabelEncoder
X = LabelEncoder().fit_transform(X[:, 0:1])
print(f'X: {X}')
y = LabelEncoder().fit_transform(y)
print(f'y: {y}')


X: [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' nan 10.0]
 ['France' 35.0 58000.0]
 ['Spain' 50.0 nan]
 ['France' 48.0 nan]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
y: ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']



X: [0 2 1 2 1 0 2 0 1 0]
y: [0 1 0 0 1 1 0 1 0 1]


c:\Users\EngSherifMostafa\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print(f'X_train.shape: {X_train.shape}')
print(f'X_test.shape: {X_test.shape}')

X_train.shape: (8,)
X_test.shape: (2,)


In [5]:
X_train_new_shape = X_train.reshape(4, 2)

print(f'X_train.shape: {X_train.shape}')
print(f'X_train_new_shape.shape: {X_train_new_shape.shape}')

print(f'X_train: {X_train}')
print(f'X_train_new_shape: {X_train_new_shape}')

print(f'X_train_new_shape type: {type(X_train_new_shape[0, 0])}')
X_train_new_shape_new_type = X_train_new_shape.astype(float)
print(f'X_train_new_shape_new_type type: {type(X_train_new_shape_new_type[0, 0])}')

X_train.shape: (8,)
X_train_new_shape.shape: (4, 2)
X_train: [1 0 2 2 0 2 0 0]
X_train_new_shape: [[1 0]
 [2 2]
 [0 2]
 [0 0]]
X_train_new_shape type: <class 'numpy.int32'>
X_train_new_shape_new_type type: <class 'numpy.float64'>


 The Pearson correlation coefficient measures the linear relationship between two dataset

* 1 means a perfect positive linear relationship.
* -1 means a perfect negative linear relationship.
* 0 means no linear relationship.

In [6]:
import numpy as np

sample_1 = np.array([1, 4, 3, 4])
sample_2 = np.array([3, 2, 4, 1])

corrcoef = np.corrcoef(sample_1, sample_2)
print(f'corrcoef:\n{corrcoef}')

corrcoef:
[[ 1.         -0.54772256]
 [-0.54772256  1.        ]]


In [7]:
sample_1 = np.random.randint(1, 50, size=(2, 1))
sample_2 = np.random.randint(1, 50, size=(2, 1))

print(f'sample_1:\n{sample_1}')
print(f'sample_2:\n{sample_2}')

sample_1:
[[ 5]
 [26]]
sample_2:
[[11]
 [23]]
