In [1]:
import pandas as pd
import os

path = r'D:\Projects\Software_Engineering\Artificial_Intelligence\Huawei_Internship_16_Sep/Datasets'

data = pd.read_csv(os.path.join(path, 'Data.csv'))
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany   NaN     10.0       Yes

In [2]:
data.isnull().sum()

Country      0
Age          1
Salary       2
Purchased    0
dtype: int64

In [3]:
data_without_nan = data.dropna()

X = data_without_nan.iloc[ : , 1:3].values
y = data_without_nan.iloc[ : , -1].values

print(f'X Before SC\n{X}\n')
print(f'y: {y}\n\n')

from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)

print(f'X After SC\n{X}')

X Before SC
[[4.4e+01 7.2e+04]
 [2.7e+01 4.8e+04]
 [3.0e+01 5.4e+04]
 [3.8e+01 6.1e+04]
 [3.5e+01 5.8e+04]
 [5.0e+01 8.3e+04]
 [3.7e+01 6.7e+04]]

y: ['No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes']


X After SC
[[ 0.92174584  0.79959182]
 [-1.41203617 -1.4025627 ]
 [-1.00019229 -0.85202407]
 [ 0.09805807 -0.209729  ]
 [-0.31378582 -0.48499832]
 [ 1.7454336   1.80891264]
 [-0.03922323  0.34080963]]


inplace=True: This parameter modifies the original data DataFrame in place

In [4]:
data = pd.read_csv(os.path.join(path, 'Data.csv'))
print(data, '\n\n')
data.dropna(inplace=True)
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany   NaN     10.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  50.0      NaN        No
7   France  48.0      NaN       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes 


   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


'''lb = LabelEncoder()
x[:, 0] = lb.fit_transform(x[:, 0])'''

In [5]:
X = data.iloc[:, :-1].values # X is numpy.ndarray
print(f'X Before encoder\n{X}\n')

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

tf = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [0])
        ],
        remainder='passthrough' # Keep other columns as-is
    )

X = tf.fit_transform(X)
print(f'X After encoder\n{X}\n')

X Before encoder
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['France' 35.0 58000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

X After encoder
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]



StandardScaler
--------------
X (Scaled) = ( X (data) - μ ) / σ

- μ is the mean of the feature.
- σ is the standard deviation of the feature.

σ = Root ( (data - μ)^2 / μ )


all features will have a mean of 0 and a standard deviation of 1

normalize
--------------
normalized(x) = X / ∥𝑥∥

Where ∥x∥ is the L2 norm (Euclidean length) of the vector.

∥𝑥∥ = Root ( X1^2 + X2^2 + X3^2 + ... )


Normalization ensures that each row (or sample) has a unit norm (L2 norm of 1), but it does not ensure that each column is independently scaled. Therefore, if one column (like your fifth column with large numbers) has much larger values than others, it will dominate the normalization process.

Solution:
If you want the features to have a more comparable range of values before normalization, you should first scale the features. This can be done using StandardScaler or MinMaxScaler from sklearn to ensure that all features have similar ranges, and then apply normalization.

In [6]:
from sklearn.preprocessing import StandardScaler, normalize

print(f'Salary Before StandardScaler:\n{X[ : , 3:5]}\n\n')
ss = StandardScaler()
X[ : , 3:5] = ss.fit_transform(X[ : , 3:5])
print(f'Salary After StandardScaler:\n{X[ : , 3:5]}\n\n')


print(f'X Before normalization:\n{X}\n\n')
nor_X = normalize(X)
print(f'X Afetr normalization:\n{nor_X}\n\n')


Salary Before StandardScaler:
[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [35.0 58000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


Salary After StandardScaler:
[[0.9217458351494651 0.7995918202669416]
 [-1.412036172994925 -1.4025627011239787]
 [-1.0001922892047383 -0.8520240707762488]
 [0.09805806756909216 -0.20972900203723024]
 [-0.3137858162210943 -0.4849983172110953]
 [1.745433602729838 1.8089126425711135]
 [-0.03922322702763667 0.3408096283104999]]


X Before normalization:
[[1.0 0.0 0.0 0.9217458351494651 0.7995918202669416]
 [0.0 0.0 1.0 -1.412036172994925 -1.4025627011239787]
 [0.0 1.0 0.0 -1.0001922892047383 -0.8520240707762488]
 [0.0 0.0 1.0 0.09805806756909216 -0.20972900203723024]
 [1.0 0.0 0.0 -0.3137858162210943 -0.4849983172110953]
 [0.0 1.0 0.0 1.745433602729838 1.8089126425711135]
 [1.0 0.0 0.0 -0.03922322702763667 0.3408096283104999]]


X Afetr normalization:
[[ 0.63385632  0.          0.          0.58425443  0.50682633]
 [ 0.          0.          0.44896

In [7]:
from sklearn.preprocessing import normalize
import numpy as np

print(f'X\n{X}\n\n')
print(f'X[:,1].reshape(1,-1): {X[:,1].reshape(1,-1)}\n\n')

# normalize: works only with 2D array
nor = normalize(np.array(X[ : , 1]).reshape(1, -1)) # (np.array(X[:,1]).reshape(1,-1)): convert 1D to 2D array
print(f'X after normalization\n{nor}')

X
[[1.0 0.0 0.0 0.9217458351494651 0.7995918202669416]
 [0.0 0.0 1.0 -1.412036172994925 -1.4025627011239787]
 [0.0 1.0 0.0 -1.0001922892047383 -0.8520240707762488]
 [0.0 0.0 1.0 0.09805806756909216 -0.20972900203723024]
 [1.0 0.0 0.0 -0.3137858162210943 -0.4849983172110953]
 [0.0 1.0 0.0 1.745433602729838 1.8089126425711135]
 [1.0 0.0 0.0 -0.03922322702763667 0.3408096283104999]]


X[:,1].reshape(1,-1): [[0.0 0.0 1.0 0.0 0.0 1.0 0.0]]


X after normalization
[[0.         0.         0.70710678 0.         0.         0.70710678
  0.        ]]
